# Generated by Django 3.2.25 on 2025-06-19 17:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_hp'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hp',
            new_name='paises',
        ),
    ]
