# Generated by Django 3.2.25 on 2025-06-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_hp_paises'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
