# Generated by Django 3.2.25 on 2025-06-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paises',
            old_name='introduccion',
            new_name='cantidades_hab',
        ),
        migrations.RenameField(
            model_name='paises',
            old_name='libros',
            new_name='cuidades_imp',
        ),
        migrations.RenameField(
            model_name='paises',
            old_name='peliculas',
            new_name='lugares_tur',
        ),
    ]
