# Generated by Django 3.2.25 on 2025-06-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20250620_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='paises',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='paises/'),
        ),
    ]
