# Generated by Django 3.2.25 on 2025-06-21 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_paises_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='paises',
            name='idi',
            field=models.CharField(default='Español', max_length=200),
        ),
        migrations.AddField(
            model_name='paises',
            name='moneda',
            field=models.CharField(default='Español', max_length=200),
        ),
        migrations.AddField(
            model_name='paises',
            name='superficie',
            field=models.CharField(default='Español', max_length=200),
        ),
    ]
