# Generated by Django 3.2.25 on 2025-06-21 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20250621_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='paises',
            name='imagenes_lug',
            field=models.ImageField(blank=True, null=True, upload_to='paises/'),
        ),
    ]
