# Generated by Django 3.2.25 on 2025-06-21 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_paises_imagenes_lug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paises',
            old_name='imagenes_lug',
            new_name='imagenes_lug1',
        ),
        migrations.AddField(
            model_name='paises',
            name='imagenes_lug2',
            field=models.ImageField(blank=True, null=True, upload_to='paises/'),
        ),
        migrations.AddField(
            model_name='paises',
            name='imagenes_lug3',
            field=models.ImageField(blank=True, null=True, upload_to='paises/'),
        ),
    ]
